# Generated by Django 5.0.6 on 2025-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_recursomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursomedico',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='estado',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('AGOT', 'Agotado'), ('VENC', 'Vencido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='lote',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recursomedico',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
