# Generated by Django 5.2.2 on 2025-07-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_recursomedico_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursomedico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='foto', verbose_name='Fotografía'),
        ),
    ]
