# Generated by Django 5.2.2 on 2025-07-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_recursomedico_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursomedico',
            name='imagen',
        ),
    ]
