# Generated by Django 5.2.2 on 2025-07-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_remove_recursomedico_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursomedico',
            name='lote',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True),
        ),
    ]
