# Generated by Django 5.0.6 on 2025-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_recursomedico_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created'],
            },
        ),
    ]
