# Generated by Django 5.2.4 on 2025-07-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
