# Generated by Django 5.2.4 on 2025-07-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_inventario_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-created'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='recursonomedico',
            options={'ordering': ['-created'], 'verbose_name': 'Recurso No Médico', 'verbose_name_plural': 'Recursos No Médicos'},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_reabastecimiento',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
