# Generated by Django 5.2.4 on 2025-07-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_paciente'),
        ('registro', '0011_alter_inventario_options_alter_medico_options_and_more'),
    ]

    operations = [
    ]
