# Generated by Django 5.2.2 on 2025-07-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_alter_inventario_options_alter_medico_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
