# Generated by Django 5.0.6 on 2025-07-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_merge_20250711_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecursoNoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRecursoNoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=15)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.paciente')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tiporecursonomedico')),
            ],
        ),
    ]
