# Generated by Django 5.2.2 on 2025-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_delete_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médico',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AlterModelOptions(
            name='recursonomedico',
            options={'ordering': ['-created'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
