# Generated by Django 5.2.2 on 2025-07-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_medico_delete_inventario_and_more'),
        ('registro', '0013_tiporecursonomedico_solicitudrecursonomedico'),
    ]

    operations = [
    ]
