# Generated by Django 5.2.2 on 2025-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_merge_20250711_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_reabastecimiento', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-created'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='recursonomedico',
            options={'ordering': ['-created'], 'verbose_name': 'Recurso No Médico', 'verbose_name_plural': 'Recursos No Médicos'},
        ),
    ]
